Birgir
orria98/hbv501g-26 pull request #22
Opened 2024-10-31 12:03 UTC by BesturogMestur

Þetta er fyrir endapuntana Retrieve recipe list (by ID) og Retrieve all recipe lists for user

2024-10-31 14:01 UTC, Sigurbj02 requested changes

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/RecipeListService.java
> +    RecipeList listById(User user, long id);
Ætti ekki að breyta þessu í findById til að hafa samræmi í Service?

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        if(list.getCreatedBy().getID() != user.getID() && list.isPrivate()){
Bæta við tékki til að passa að createdBy sé ekki null

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +     * Get all recipic that the sesson user has
Passa að það er ekki hægt að vita að þetta sé user sem er í session

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> getAllRecipeLists(User user){
Er þessi aðferð nauðsynleg? Hún er notuð einu sinni. Ef það á að halda henni væri sniðugt að breyta nafninu, því það er bara verið að sækja lista frá einum user

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> findAllUserRecipeList(long id){
þetta sækir ekki alla lista, bara private. ath þetta

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Controllers/RecipeListController.java
> +    public RecipeList getRecipesListById(HttpSession session, @PathVariable(value = "id") long id){
getRecipeListById (ekki getRecipe_s_ListById)

2024-10-31 14:01 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Controllers/RecipeListController.java
> +     * Find and return the Recipe list that a
Skoða lýsingar aðeins

2024-10-31 15:16 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/RecipeListService.java
> +    RecipeList listById(User user, long id);
ég er búinn að gera það hjá mér

2024-10-31 15:17 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +     * Get all recipic that the sesson user has
hef þetta enþá svon því það er létta að test kóðan með þessu en munn laga það þegar ég er búinn að gera allar hinar skipainar

2024-10-31 15:22 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> getAllRecipeLists(User user){
buinn að beryta því

2024-10-31 15:23 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Controllers/RecipeListController.java
> +    public RecipeList getRecipesListById(HttpSession session, @PathVariable(value = "id") long id){
lagað

2024-10-31 15:26 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Controllers/RecipeListController.java
> +     * Find and return the Recipe list that a
lagað

2024-10-31 15:28 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> findAllUserRecipeList(long id){
if( **!** recipeList.isPrivate()){
                out.add(recipeList);
            }

það er ekki það sem hann geri hann sækkir alla lista sem eru ekki private

2024-11-01 08:44 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        if(list.getCreatedBy().getID() != user.getID() && list.isPrivate()){
eftir því hvering kóinn er settur upp þá má ekki vera til Recipielist með createdBy NULL því ef þú skoðar save aðferin í sama class þá sérð þú þetta:
 /**
     * A new list cannot be created without a user logged in
     * 
     * @param user        - the current user
     * @param title       - title of the new list
     * @param description - optional description for the list
     * @param isPrivate   - optionally declare whether the list is private. false by
     *                    default.
     */
    public RecipeList save(User user, String title, String description, boolean isPrivate) {
        **if (user == null)
            return null;**
        return recipeListRepository.save(new RecipeList(user, title, description, isPrivate));
    }
    
svo ef það er til createdBy NULL þá er það vill í save afrinni ekki hér

2024-11-01 11:41 UTC, Sigurbj02 requested changes
Það voru nokkur atriði sem ég sá ekki breytingar á og finnst ekki hafa verið útskýrðir

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> findAllUserRecipeList(long id){
Sorry, átti við að þetta sæki bara það sem er ekki private, en userinn þarf að geta sótt sína eigin private lista

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        System.err.println("here");
Gleymdist að taka út?

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +     * Get all recipic that the sesson user has
Ég fatta ekki hvernig þetta hefur áhrif á testing, en það á ekki að hafa auka hluti fyrir testing á develop. Ef það er eitthvað sem er ekki lokaútgáfa ætti það að koma fram

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        if(list.getCreatedBy().getID() != user.getID() && list.isPrivate()){
Af hverju ekki að passa það hér? Kóðinn er ennþá að breytast, og við viljum að hlutir virki þó eitthvað breytist

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Controllers/RecipeListController.java
> +    public RecipeList getRecipesListById(HttpSession session, @PathVariable(value = "id") long id){
Þetta er á fleiri stöðum

2024-11-01 11:41 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> getAllRecipeListsForUser(User user){
Hver er munurinn á getAllRecipeListsForUser og findAllUserRecipeList? Skoða notkun og lýsingu, en er ekki óþarfi að hafa bæði?

2024-11-01 14:09 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        if(list.getCreatedBy().getID() != user.getID() && list.isPrivate()){
lagað

2024-11-01 14:09 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +        System.err.println("here");
lagað

2024-11-01 14:13 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> getAllRecipeListsForUser(User user){
já það er óþari en þetta gerir kóðan hraðviakri ef áhveðinn skillið eru til staðar, þau virka eins nem getAllRecipeListsForUser nær í all listan hjá useri á þess að skoða hvor þau eru priveat eða ekki

2024-11-04 10:11 UTC, Sigurbj02 requested changes
passa að path sé rétt stafsett í Controller aðferðum, og að heiti aðferða sé rétt stafsett. Ennþá tvær aðferðir með sömu lýsingu sem gera ekki það sama

2024-11-04 10:11 UTC, Sigurbj02 commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> findAllUserRecipeList(long id){
Ekki leyst

2024-11-04 13:02 UTC, BesturogMestur commented on src/main/java/hbv501g/recipes/Services/Implementation/RecipeListServiceImplementation.java
> +    public List<RecipeList> findAllUserRecipeList(long id){
það á ekki að gera það það er specal case fall sem sægir ef noandinn er að ná í sinn eigin lista það hetir getAllRecipeLists þetta er falli ef notani er ekki sá sammi.

2024-11-05 09:09 UTC, Sigurbj02 approved these changes

2024-11-05 09:13 UTC, merged